services:
  cedardb:
    build:
      context: .                      
      dockerfile: Dockerfile                        
    container_name: cedardb_runner  
    ports:
      - "5432:5432"                   
    env_file:
      - .env                                       
    volumes:
      - ./data:/data
      - ./sql:/sql                  
      - cedardb_data:/var/lib/cedardb/data                  

volumes:
  cedardb_data:
    name: cedardb_data                   
