services:
  cedar:
    container_name: cedar
    image: cedardb
    env_file:
      - .env 
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
      - cedardb_data:/var/lib/cedardb/data #make db persistent 
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: ae3e-plotly-panel
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 100ms
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    ports:
      - 3000:3000
    depends_on:
      - cedar
    volumes:
      - ./grafana:/etc/grafana/provisioning #to preload configs in grafana
      - grafana_data:/var/lib/grafana #to persist grafana data
  renderer:
    container_name: grafana_renderer
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

  replayer:
    build:
      context: ./scripts/replay
    image: replay-app
    profiles:
      - manual
    network_mode: "host"
    env_file: .env
    volumes:
      - ./data/prices:/prices
    pull_policy: build 

volumes:
  cedardb_data:
    name: cedardb_data   
  grafana_data:
    name: grafana_data                