services:
  cedar:
    container_name: cedar
    image: cedardb
    restart: always
    env_file:
      - .env 
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
      - cedardb_data:/var/lib/cedardb/data #make db persistent 
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
    ports:
      - 3000:3000
    depends_on:
      - cedar
    volumes:
      - ./grafana:/etc/grafana/provisioning #to preload configs in grafana
      - grafana_data:/var/lib/grafana #to persist grafana data

  replayer:
    build:
      context: ./scripts/replay
    image: replay-app
    profiles:
      - manual
    network_mode: "host"
    env_file: .env
    volumes:
      - ./data/prices:/data #prices folder mapped to /data
    pull_policy: build 

volumes:
  cedardb_data:
    name: cedardb_data   
  grafana_data:
    name: grafana_data                