{
 "title": "Current Fuel Prices by Area",
 "description": "Real-time analysis of the fuel prices in one area",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "fuel", "label": "Fuel", "query": "diesel, e5, e10" },
   { "name": "latitude", "label": "Latitude", "query": "52.50383" },
   { "name": "longitude", "label": "Longitude", "query": "13.3936" },
   { "name": "dst_threshold", "label": "Radius (km)", "query": "30" },
   { "name": "l_100km", "label": "Fuel Consumption (L/100km)", "query": "7" },
   { "name": "liters", "label": "Liters", "query": "40" },
   {
    "name": "time_granularity",
    "label": "Time Granularity",
    "query": "select i  || 'h' as min FROM generate_series(1, 4) as i\nunion all\nselect i*5  || 'm' as min FROM generate_series(1, 11) as i;"
   },
   {
    "name": "now_t",
    "query": "SELECT FORMAT(MAX(time), 'yyyy-MM-dd HH:mm:ss') AS now_t FROM prices;\n"
   },
   {
    "name": "time_diff",
    "query": "SELECT EXTRACT(EPOCH FROM (NOW() - MAX(time)))::INT || 's' AS time_difference\nFROM prices;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Prices Around Location ($latitude, $longitude) within $dst_threshold km",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Actual Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select max(time) from prices" }
   ]
  },
  {
   "title": "Open Stations In The Area",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, close_enough_stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime_open AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), \nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n) -----------\n-- Open Stations In The Area\nSELECT COUNT(*) from open_stations;"
    }
   ]
  },
  {
   "title": "Average $fuel Price In The Area",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, close_enough_stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime_open AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), \nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n) -----------\n-- AVG Prices\nSELECT avg_price from stats;"
    }
   ]
  },
  {
   "title": "Prices In The Area",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, close_enough_stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime_open AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), -----------\n-- Prices In The Area\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n),\nprices_z_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM open_curr_price p,stats\n)\nSELECT station_id, brand, latitude, longitude, price, dst_km, z_score\nFROM prices_z_scores;"
    },
    {
     "rawSql": "select $latitude as latitude, $longitude as longitude;"
    }
   ]
  },
  {
   "title": "Best place to fuel up!",
   "type": "geomap",
   "description": "For $liters L with a consumption of $l_100km L/100km",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, close_enough_stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime_open AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), -----------\nrankings AS (\n    SELECT s.*,  RANK() OVER (ORDER BY total_cost ASC) AS position\n    FROM (\n        SELECT pr.*, (price * 40) + (dst_km * ((7/100)*price)) as total_cost\n        FROM open_curr_price pr\n        ) as s\n)\nSELECT station_id, brand, latitude, longitude, price, dst_km, total_cost, position\nFROM rankings;\n"
    },
    {
     "rawSql": "select $latitude as latitude, $longitude as longitude;"
    }
   ]
  },
  {
   "title": "Recent Prices In The Area",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT \n    '$now_t'::TIMESTAMP as end_t,\n    '${time_granularity}'::INTERVAL AS time_granularity,\n    ( $__timeTo()::TIMESTAMP - $__timeFrom()::TIMESTAMP) as range_t,\n    end_t - range_t as start_t,\n    EXTRACT(EPOCH FROM time_granularity) AS interval_seconds,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold,\n),\ntime_series AS (\n    SELECT  start_t + (((i-1) * interval_seconds) * INTERVAL '1 second') AS bucket_start, \n            bucket_start + (interval_seconds * INTERVAL '1 second') as bucket_end,\n            EXTRACT(dow FROM bucket_start) AS day_of_week, -- needed only for day_bit\n            (CASE WHEN day_of_week = 0 THEN 6 ELSE day_of_week -1 END ) as day_bit --needed for flextime stations\n    FROM param, generate_series(1 , (EXTRACT(EPOCH FROM (end_t - start_t)) / interval_seconds)) AS i\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM close_enough_stations s, param\n    WHERE EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND p.time BETWEEN end_t - INTERVAL '3 day' AND end_t)-- avoid inactive stations\n),\nflextime_buckets AS(\n    SELECT bucket_start, s.station_id, bucket_start::date + open_time as from_t , bucket_end::date + close_time as to_t\n    FROM time_series, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id  AND first_active <= bucket_start\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND (bucket_start::date + open_time, bucket_start::date + close_time) OVERLAPS (bucket_start, bucket_end) -- opening hours?\n),\nalwaysopen_buckets AS (\n    SELECT bucket_start, station_id, bucket_start as from_t , bucket_end as to_t\n    FROM time_series, active_stations WHERE always_open AND first_active <= bucket_start\n),\nstations_time_series AS (\n    SELECT * FROM  flextime_buckets UNION ALL SELECT * FROM alwaysopen_buckets\n),\nstations_prices AS (\n   SELECT time as valid_from, diesel as price, s.*\n    FROM param, prices p, active_stations s\n    WHERE s.station_id = p.station_uuid\n    AND diesel_change IN (1,3) AND time BETWEEN param.start_t AND param.end_t\n\n    UNION ALL\n\n    SELECT  param.start_t AS valid_from, price, s.* --add last event before start\n    FROM param, active_stations s, (\n        SELECT time as valid_from, diesel as price\n        FROM prices pp, param\n        WHERE s.station_id = pp.station_uuid AND diesel_change IN (1,3)\n        AND time <= start_t AND time >= start_t - '2 day'::INTERVAL \n        ORDER BY time DESC LIMIT 1\n    ) p\n), \nprices_intervals AS (\n    SELECT LEAD(valid_from, 1, param.end_t) OVER (PARTITION BY station_id ORDER BY valid_from) AS valid_until, sp.*\n    FROM stations_prices sp, param\n),\nprices_time_series AS (\n    SELECT bucket_start, EXTRACT(EPOCH FROM (LEAST(to_t, valid_until) - GREATEST(from_t, valid_from))) as duration_seconds, p_int.*\n    FROM  stations_time_series ts, prices_intervals p_int,\n    WHERE ts.station_id = p_int.station_id AND (valid_from,valid_until) OVERLAPS (from_t, to_t)\n)\nselect bucket_start as datetime, SUM(price * duration_seconds) / SUM(duration_seconds) as avg_diesel_price\nfrom prices_time_series\ngroup by datetime\norder by datetime;"
    }
   ]
  },
  {
   "title": "Top Brands In The Area",
   "type": "xychart",
   "description": "Hover, for brand details",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nclose_enough_stations AS (\n    SELECT s.*\n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, close_enough_stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime_open AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), \nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n) -----------\n-- Top Brands In The Area\nSELECT brand, avg(price) as avg_price, COUNT(*) n_stations\nFROM (\n    SELECT pr.*, (price * 40) + (dst_km * ((7/100)*price)) as total_cost\n    FROM open_curr_price pr\n    )\nWHERE brand <> ''\nGROUP BY brand\nORDER BY n_stations DESC LIMIT 10;"
    }
   ]
  }
 ]
}