{
 "title": "Point-In-Time Fuel Prices",
 "time": { "from": "2024-01-31T17:00:00.000Z", "to": "2024-01-31T17:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "fuel", "label": "Fuel", "query": "diesel, e5, e10" },
   { "name": "create_clusters" }
  ]
 },
 "panels": [
  {
   "title": "Open Stations at ${__to}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n)\nSELECT \n    (select count(station_id) from flextime) as n_flextime,\n    (select count(station_id) from alwaysopen) as n_alwaysopen,\n    n_flextime + n_alwaysopen as n_open_stations;"
    }
   ]
  },
  {
   "title": "Average $fuel price at ${__to}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n)\nselect avg(price) as average_price from curr_prices;"
    }
   ]
  },
  {
   "title": "Distribution of $fuel prices at${__to}",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n)\nselect price from curr_prices;"
    }
   ]
  },
  {
   "title": "Top 10 Brands ($fuel price vs number of stations)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT * FROM (\n    SELECT brand, COUNT(*) n_stations, AVG(price) average_price\n    FROM curr_prices\n    WHERE brand <> ''\n    GROUP BY brand \n    ORDER BY n_stations DESC LIMIT 10\n) ORDER BY average_price;"
    }
   ]
  },
  {
   "title": "Outliers stats for $fuel at ${__to}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT\n    (select count(*) from prices_scores) as n_open_stations,\n    (select count(*) from prices_scores where abs(z_score) > 3) as n_outliers,\n    (n_outliers::numeric / n_open_stations) * 100 as percentage_outliers;"
    }
   ]
  },
  {
   "title": "Distribution of $fuel prices at${__to} [NO OUTLIERS]",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT ${fuel:raw} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND ${fuel:raw}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nselect price from prices_scores where abs(z_score) <= 3"
    }
   ]
  },
  { "title": "City Center ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cities by City Center ($fuel price vs number of stations)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT city, count(*) as n_open_station, avg(price) as average_price\nFROM  curr_prices\nGROUP BY city HAVING count(*) > 40\nORDER BY average_price;"
    }
   ]
  },
  {
   "title": "Cities Centers Prices",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT city, count(*) as n_open_station, avg(price) as average_price\nFROM  curr_prices\nGROUP BY city HAVING count(*) > 40\nORDER BY average_price;"
    }
   ]
  },
  { "title": "City Areas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Cities by City Area ($fuel price vs number of stations)",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT short_cluster_name, count(*) as n_open_station, avg(price) as average_price\nFROM curr_prices p, stations_clusters sc\nWHERE p.station_id = sc.station_id\nGROUP BY cluster_id, short_cluster_name\nORDER BY average_price;"
    }
   ]
  },
  {
   "title": "Cities Centers Prices",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT $__timeTo()::TIMESTAMP AS time_t, \n        (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n),\nactive_stations AS(\n    SELECT s.id as station_id, s.*\n    FROM param, stations s \n    WHERE first_active <= time_t AND\n    EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND time BETWEEN time_t - INTERVAL '3 day' AND time_t)-- avoid inactive stations\n), \nalwaysopen AS(\n    SELECT s.* FROM active_stations s WHERE s.always_open \n),\nflextime AS(\n    SELECT s.*\n    FROM param, stations_times st, active_stations s\n    WHERE st.station_id = s.station_id\n        AND (days & (1 << (day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT * FROM flextime\n),\ncurr_prices AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t \n            AND time >= time_t - INTERVAL '3 day'\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM curr_prices\n),\nprices_scores AS (\n    SELECT p.*, (p.price - avg_price) / std_dev_price AS z_score\n    FROM curr_prices p,stats\n)\nSELECT short_cluster_name, count(*) as n_open_station, avg(price) as average_price\nFROM curr_prices p, stations_clusters sc\nWHERE p.station_id = sc.station_id\nGROUP BY cluster_id, short_cluster_name\nORDER BY average_price;"
    }
   ]
  }
 ]
}