{
 "title": "Real-Time",
 "description": "Visualizations of Real-Time Fuel Prices",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "replay_time",
    "label": "Replay Time",
    "query": "select format(max(time), 'YYYY-MM-DD HH:mm:ss') from prices;"
   },
   { "name": "fuel", "label": "Fuel", "query": "diesel, e5, e10" },
   {
    "name": "cities",
    "label": "Cities",
    "query": "WITH param AS (\n    SELECT max(time) as time_t from prices\n)\nSELECT city FROM stations, param\nWHERE EXISTS (SELECT station_uuid from prices p where p.station_uuid = id AND p.time BETWEEN (time_t - INTERVAL '2 day') AND time_t)\nGROUP BY city HAVING COUNT(*) > 40\nORDER BY COUNT(*)  DESC;"
   },
   { "name": "latitude", "label": "Latitude", "query": "52.50383" },
   { "name": "longitude", "label": "Longitude", "query": "13.3936" },
   { "name": "dst_threshold", "label": "Radius (km)", "query": "30" },
   { "name": "l_100km", "label": "Fuel Consumption (L/100km)", "query": "7" },
   { "name": "liters", "label": "Liters", "query": "40" }
  ]
 },
 "panels": [
  {
   "title": "Insertions per Seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "CREATE TEMP TABLE IF NOT EXISTS row_count_temp (\n    time TIMESTAMP,\n    row_count BIGINT\n);\n\nSELECT ((select count(*) from prices) - row_count )  / EXTRACT(EPOCH FROM (NOW() - time)) as ins_sec\nFROM row_count_temp WHERE time = (select max(time) from row_count_temp);\n\n\nINSERT INTO row_count_temp SELECT NOW(), count(*) from prices;"
    }
   ]
  },
  {
   "title": "Average $fuel Price Now ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) as time_t,\n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    '2 day'::INTERVAL as activity_interval\n    from prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param\n    WHERE s.always_open\n    AND EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND p.time BETWEEN time_t - activity_interval AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n    AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n    AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n    AND EXISTS (SELECT station_uuid from prices p where p.station_uuid = s.id AND p.time BETWEEN time_t - activity_interval AND time_t)  -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen\n    UNION ALL -- alwaysopen and flextime stations do not overlap\n    SELECT *  FROM flextime_open\n),\nopen_curr_price AS (\n    SELECT open_stations.*, p.price, p.time\n    FROM open_stations, param, \n        (\n            SELECT ${fuel} as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - activity_interval --limit\n            AND ${fuel}_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n), \nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n)\nselect avg_price as avg_diesel_price from stats;"
    }
   ]
  },
  {
   "title": "Open Stations Now",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    FROM prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param \n    WHERE s.always_open\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n        AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen\n    UNION ALL -- alwaysopen and flextime stations do not overlap\n    SELECT *  FROM flextime_open\n)\nselect count(station_id) as cnt from open_stations;"
    }
   ]
  },
  {
   "title": "Prices Around Location ($latitude, $longitude) within $dst_threshold km",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Prices Status Around Location",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param \n    WHERE s.always_open\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n        AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nclose_stations AS (\n    SELECT s.* \n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM open_stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nopen_curr_price AS (\n    SELECT close_stations.*, p.price, p.time\n    FROM close_stations, param, \n        (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n)\nSELECT station_id, latitude, longitude, price,  (price - avg_price) / std_dev_price AS z_score\nFROM open_curr_price p, stats\nWHERE ABS((p.price - stats.avg_price) / stats.std_dev_price) <= 3;\n"
    },
    {
     "rawSql": "select $latitude as latitude, $longitude as longitude;"
    }
   ]
  },
  {
   "title": "Open Stations Around Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param \n    WHERE s.always_open\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n        AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nclose_stations AS (\n    SELECT s.* \n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM open_stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n)\nselect count(*) from close_stations;"
    }
   ]
  },
  {
   "title": "Best place to fuel up?",
   "type": "geomap",
   "description": "For $liters L with a consumption of $l_100km L/100km",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param \n    WHERE s.always_open\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n        AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nclose_stations AS (\n    SELECT s.* \n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM open_stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nopen_curr_price AS (\n    SELECT close_stations.*, p.price, p.time\n    FROM close_stations, param, \n        (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n)\nSELECT s.* , ROW_NUMBER() OVER (ORDER BY total_cost ASC) AS position\nFROM (\n    SELECT station_id, brand, latitude, longitude, price, dst_km, (price * $liters) + (dst_km * (($l_100km /100)*price)) as total_cost\n    FROM open_curr_price\n    ) as s;\n"
    },
    {
     "rawSql": "select $latitude as latitude, $longitude as longitude;"
    }
   ]
  },
  {
   "title": "AVG $fuel Price Around Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH param AS (\n    SELECT max(time) AS time_t, \n    (CASE WHEN EXTRACT(dow FROM time_t) = 0 THEN 6 ELSE EXTRACT(dow FROM time_t) -1 END ) as day_bit,\n    $latitude as lat, $longitude as lon, $dst_threshold AS dst_threshold\n    FROM prices\n),\nalwaysopen AS(\n    SELECT s.id as station_id, s.always_open, city, brand, latitude, longitude\n    FROM stations s, param \n    WHERE s.always_open\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nflextime_open AS(\n    SELECT station_id, false as always_open, city, brand, latitude, longitude\n    FROM stations_times st, stations s, param\n    WHERE st.station_id = s.id\n        AND (st.days & (1 << (param.day_bit))) > 0 -- open day?\n        AND time_t BETWEEN time_t::date + open_time AND time_t::date + close_time -- opening hours?\n        AND EXISTS (SELECT station_uuid FROM prices WHERE station_uuid = id AND time  BETWEEN time_t - INTERVAL '2 day' AND time_t) -- avoid inactive stations\n),\nopen_stations AS (\n    SELECT * FROM alwaysopen UNION ALL SELECT *  FROM flextime_open\n),\nclose_stations AS (\n    SELECT s.* \n    FROM param, ( \n        SELECT s.*, 2 * 6371 * ATAN2(\n                SQRT(\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ),\n                SQRT(1 - (\n                    POWER(SIN(RADIANS(lat - s.latitude) / 2), 2) +\n                    COS(RADIANS(s.latitude)) * COS(RADIANS(lat)) *\n                    POWER(SIN(RADIANS(lon - s.longitude) / 2), 2)\n                ))\n            ) AS dst_km\n        FROM open_stations s\n    ) as s\n    WHERE dst_km <= dst_threshold\n),\nopen_curr_price AS (\n    SELECT close_stations.*, p.price, p.time\n    FROM close_stations, param, \n        (\n            SELECT diesel as price ,time\n            FROM prices\n            WHERE station_uuid = station_id AND time <= time_t\n            AND time >= time_t - INTERVAL '2 day' --limit\n            AND diesel_change IN (1, 3)\n            ORDER BY time DESC\n            LIMIT 1\n        ) p\n),\nstats AS (\n    SELECT AVG(price) AS avg_price, STDDEV(price) AS std_dev_price FROM open_curr_price\n)\nselect avg_price from stats;"
    }
   ]
  }
 ]
}