name: Weekly Prepare New Stations Dataset

on:
  schedule:
    - cron: "0 12 * * 3" 
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          pip install requests

      - name: Download Newest Stations Dataset
        run: |
          echo "Current date: $(date)"
          echo "Yesterday's date: $(date --date="yesterday" "+%Y-%m-%d")"

          bash ./scripts/download.sh -s

          LINE_COUNT=$(wc -l < data/stations_original.csv)
          echo "Number of lines in stations_original.csv: $LINE_COUNT"
          
          if [ "$LINE_COUNT" -lt 100 ]; then
            echo "Error: stations_original.csv has fewer than 100 lines ($LINE_COUNT lines)"
            exit 1
          fi
      
      - name: Prepare Stations Dataset
        run: python scripts/prepare_stations.py data/stations_original.csv data/zuordnung_plz_ort.csv

      - name: Add new data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/stations.csv data/stations_times.csv
          git commit -m "weekly update of stations dataset"
          git push
